### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by jackjackamerica** [droberson/icmp-backdoor#1]
i don't understand # how should we setup the listener in our server
when we starting pinging our server from the target?

**Comment by droberson** [comment]
Here is a screen shot of it in use:

http://storage5.static.itmages.com/i/17/0801/h_1501587152_5978738_ca7c1ecd9f.png

The top terminal is running the ICMP listener, the middle terminal is running the netcat listener, and the bottom terminal is sending the ping. All three are different machines
